module.exports = {
  'NEW_CHILD_BRANCH_REQUEST': 0,
  'CHILD_BRANCH_REQUEST_ANSWERED': 1,
  'BRANCH_MOVED': 2,
  'ADDED_MODERATOR': 3,
  'REMOVED_MODERATOR': 4,
  'NEW_COMMENT': 5,
  'NEW_REPLY': 6
};
